### ISSUE TITLE
No Apache redirect of https://cardiac.nottingham.ac.uk/ActionPotential/

### ISSUE THREAD

**Issue by flawmop** [CardiacModelling/ap-nimbus#64]
If I point the browser at https://cardiac.nottingham.ac.uk/ActionPotential/ I get a "404 Not Found". We should be auto-redirecting to https://cardiac.nottingham.ac.uk/ActionPotentialPortal/

**Comment by MauriceHendrix** [comment]
I've added a redirect to the apache config
